version: "3.7"
services:
  web:
    image: nginx:alpine
    container_name: ${APP_NAME}-web
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    build: ./docker
    container_name: ${APP_NAME}-php
    working_dir: /var/www/
    user: 6thmen:6thmen
    volumes:
      - .:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: ${APP_NAME}-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./docker/pgsql/:/docker-entrypoint-initdb.d/

  adminer:
    image: adminer
    container_name: ${APP_NAME}-adminer
    environment:
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: db
    ports:
      - 8080:8080

  node:
    build:
      context: ./docker/nodejs
    command: npm run watch
    container_name: ${APP_NAME}-node
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000

#  memcached:
    #    image: memcached:latest
    #    ports:
    #      - 11211:11211
    #    command: -m 64
